backend/backend/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/movies/urls.py
from django.urls import path

from .views import MovieListView, MovieDetailView, ReviewCreateView

urlpatterns = [
    path('', MovieListView.as_view(), name='movie_list'),
    path('<slug:slug>/', MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>', ReviewCreateView.as_view(), name='add_review'),
]

backend/movies/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class Category(models.Model):
    """
    Category Model
    """
    name = models.CharField('Category', max_length=150)
    description = models.TextField('Description')
    slug = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Actor(models.Model):
    """
    Actors and Producer Model
    """
    name = models.CharField('Name', max_length=100)
    age = models.PositiveSmallIntegerField('Age', default=0)
    description = models.TextField('Description')
    image = models.ImageField('Image', upload_to='actors/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Actors and Producers'
        verbose_name_plural = 'Actors and Producers'


class Genre(models.Model):
    """
    Genre Model
    """
    name = models.CharField('Name', max_length=100)
    description = models.TextField('Description')
    slug = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'


class Movie(models.Model):
    """
    Movie Model
    """
    title = models.CharField('Title', max_length=100)
    tagline = models.CharField('Tagline', max_length=100, default='')
    description = models.TextField('Description')
    poster = models.ImageField('Poster', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Release date', default=2023)
    country = models.CharField('Country', max_length=30)
    producers = models.ManyToManyField(Actor, verbose_name='Producers', related_name='film_producer')
    actors = models.ManyToManyField(Actor, verbose_name='Actors', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='Genres')
    world_premiere = models.DateField('World premiere', default=date.today)
    budget = models.PositiveIntegerField('Budget', default=0, help_text='Provide amount in USD')
    fees_in_usa = models.PositiveIntegerField('Fees in USA', default=0, help_text='Provide amount in USD')
    fees_in_world = models.PositiveIntegerField('Fees in World', default=0, help_text='Provide amount in USD')
    category = models.ForeignKey(Category, verbose_name='Category', on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField('Draft', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.slug})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'


class MovieShots(models.Model):
    """
    Movie Shots Model
    """
    title = models.CharField('Title', max_length=100)
    description = models.TextField('Description')
    image = models.ImageField('Image', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, verbose_name='Film', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Shot from movie'
        verbose_name_plural = 'Shots from movie'


class RatingStar(models.Model):
    """
    Rating Star Model
    """
    value = models.SmallIntegerField('Value', default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Rating star'
        verbose_name_plural = 'Rating stars'


class Rating(models.Model):
    """
    Rating Model
    """
    ip = models.CharField('IP', max_length=15)
    star = models.ForeignKey(RatingStar, verbose_name='Stars', on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name='Film', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.start} - {self.movie}'

    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Rating'


class Reviews(models.Model):
    """
    Reviews Model
    """
    email = models.EmailField()
    name = models.CharField('Name', max_length=100)
    text = models.TextField('Message', max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Parent', on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name='Film', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

backend/movies/forms.py
from django import forms

from .models import Reviews


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')

backend/movies/views.py
from django.db.models import Q
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, View, CreateView

from .models import Movie
from .forms import ReviewForm


class MovieListView(ListView):
    model = Movie

    def get_queryset(self):
        return Movie.objects.filter(draft=False)


class MovieDetailView(DetailView):
    model = Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewForm()
        return context


class ReviewCreateView(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)

        if form.is_valid():
            form = form.save(commit=False)

            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))

            form.movie = movie
            form.save()

        return redirect(movie.get_absolute_url())


# class JsonFilterMoviewsView(ListView):
#     def get_queryset(self):
#         queryset = Movie.objects.filter(
#             Q(year__in=self.request.GET.getlist('year')) |
#             Q(genres__in=self.request.GET.getlist('genre'))
#         ).distinct().values('title', 'tagline', 'url', 'poster')
#
#         return queryset
#
#     def get(self, request, *args, **kwargs):
#         queryset = list(self.get_queryset())
#         return JsonResponse({'movies': queryset}, safe=False)

backend/movies/templates/movies/movie_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<div class="left-ads-display col-lg-9">
    <div class="row">
        <div class="desc1-left col-md-3">
            <img src="{{ object.poster.url }}" class="img-fluid" alt="{{ object.title }}">
        </div>
        <div class="desc1-right col-md-9 pl-lg-4">
            <h3 style="outline: none; cursor: inherit;">
                {{ object.title }}</h3>
            <ul>
                <li style="list-style: none"><span><b>Год:</b> {{ object.year }}</span></li>
                <li style="list-style: none"><span><b>Страна:</b> {{ object.country }}</span>
                </li>
                <li style="list-style: none"><span><b>Слоган:</b> «{{ object.tagline }}»</span>
                </li>
                <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                    {% for producer in object.producers.all %}
                                        {{ producer.name }}
                                    {% endfor %}
                                    </span>
                </li>
                <li style="list-style: none">
                                    <span><b>Актеры:</b>
                                    {% for actor in object.actors.all %}
                                        {{ actor.name }}
                                    {% endfor %}
                                    </span>
                </li>
                <li style="list-style: none">
                                    <span><b>Жанр:</b>
                                    {% for genre in object.genres.all %}
                                        {{ genre.name }}
                                    {% endfor %}
                                    </span>
                </li>
                <li style="list-style: none">
                    <span><b>Премьера в мире:</b> {{ object.world_premiere }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Бюджет:</b> ${{ object.budget }}</span></li>
                <li style="list-style: none">
                    <span><b>Сборы в США:</b> ${{ object.fees_in_usa }}</span></li>
                <li style="list-style: none">
                    <span><b>Сборы в мире:</b> ${{ object.fees_in_world }}</span>
                </li>
                <li style="list-style: none">
                    <a href="#"><b>Рейтинг:</b>
                        <span class="fa fa-star" aria-hidden="true"></span>
                        <span class="fa fa-star" aria-hidden="true"></span>
                        <span class="fa fa-star" aria-hidden="true"></span>
                        <span class="fa fa-star" aria-hidden="true"></span>
                        <span class="fa fa-star" aria-hidden="true"></span>
                        <span>5.0</span>
                    </a>
                </li>
            </ul>
            <div class="share-desc">
                <div class="share">
                    <h4 style="outline: none; cursor: inherit;">
                        Share:</h4>
                    <ul class="w3layouts_social_list list-unstyled">
                        <li>
                            <a href="#" class="w3pvt_facebook"
                               style="outline: none; cursor: inherit;">
                                <span class="fa fa-facebook-f" style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="w3pvt_twitter" style="outline: none; cursor: inherit;">
                                <span class="fa fa-twitter" style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="w3pvt_dribble" style="outline: none; cursor: inherit;">
                                <span class="fa fa-dribbble" style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing" style="outline: none; cursor: inherit;">
            О фильме {{ object.title }}</h3>
        <p>
            {% for image in object.movieshots_set.all %}
            <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.description }}">
            {% endfor %}
        </p>
        <p style="outline: none; cursor: inherit;">
            {{ object.description }}
        </p>
    </div>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <div class="contact-single">
                <h3>
                    <span class="sub-tittle">{{ object.reviews_set.count }}</span>Оставить отзыв
                </h3>
                {% include './review_form.html' %}
            </div>
        </div>
        {% for review in object.get_review %}
        <div class="media py-5">
            <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
            <div class="media-body mt-4">
                <h5 class="mt-0">{{ review.name }}</h5>
                <p class="mt-2">{{ review.text }}</p>
                <a href="#fromReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Replay</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script>
    function addReview(name, id) {
        document.getElementById("parent").value = id;
        document.getElementById("contactcomment").innerText = `${name}, `;
    }
</script>
{% endblock %}

backend/movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% block content %}
<div class="left-ads-display col-lg-9">
    <div class="row">
        {% for movie in object_list %}
        <div class="col-md-4 product-men">
            <div class="product-shoe-info editContent text-center mt-lg-4">
                <div class="men-thumb-item">
                    <img src="{{ movie.poster.url }}" class="img-fluid" alt="{{ movie.title }}">
                </div>
                <div class="item-info-product">
                    <h4 class="">
                        <a href="{% url 'movie_detail' movie.slug %}" class="editContent">
                            {{ movie.title }}
                        </a>
                    </h4>
                    <div class="product_price">
                        <div class="grid-price">
                                            <span class="money editContent">
                                                {{ movie.tagline }}
                                            </span>
                        </div>
                    </div>
                    <ul class="stars">
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a>
                        </li>
                        <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a>
                        </li>
                        <li><a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

backend/movies/templates/movies/review_form.html
<form action="{% url 'add_review' object.id %}" method="POST" class="mt-4" id="formReview">
    {% csrf_token %}
    <input type="hidden" name="parent" value="" id="parent">
    <div class="form-group editContent">
        <label for="contactcomment" class="editContent">Ваш комментарий*</label>
        <textarea class="form-control border" rows="5" id="contactcomment" required="" name="text"></textarea>
    </div>
    <div class="d-sm-flex">
        <div class="col-sm-6 form-group p-0 editContent">
            <label for="contactusername" class="editContent">Имя*</label>
            <input type="text" class="form-control border" id="contactusername" required="" name="name">
        </div>
        <div class="col-sm-6 form-group ml-sm-3 editContent"
             style="outline: none; cursor: inherit;">
            <label for="contactemail" class="editContent">Email*</label>
            <input type="email" class="form-control border" id="contactemail" required="" name="email">
        </div>
    </div>

    <button type="submit" class="mt-3 btn btn-success btn-block py-3">Отправить</button>
</form>

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Netflix{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
</head>
<body>
<div id="page" class="page">
    {% include 'inc/_header.html' %}
    {% include 'inc/_breadcrumb.html' %}
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        <div class="container-fluid py-md-3">
            <div class="row">
                {% include 'inc/_sidebar.html' %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </section>
    {% include 'inc/_footer.html' %}
</div>
</body>
</html>

backend/templates/inc/_breadcrumb.html
<ol class="breadcrumb editContent">
    <li class="breadcrumb-item">
        <a href="index.html" class="editContent">Home</a>
    </li>
    <li class="breadcrumb-item active editContent">Single Page</li>
</ol>

backend/templates/inc/_footer.html
<footer class="editContent">
    <div class="container">
        <div class="row footer-top">
            <div class="col-lg-4 footer-grid_section_w3layouts">
                <h2 class="logo-2 mb-lg-4 mb-3">
                    <a href="index.html" class="editContent">
                        <span class="fa" aria-hidden="true">
                            Django School
                        </span>
                    </a>
                </h2>
                <p class="editContent">
                    Канал для программистов и людей, которые хотят развиваться в сфере IT.
                    Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                    и многое другое.
                </p>
                <h4 class="sub-con-fo ad-info my-4 editContent">Catch on Social</h4>
                <ul class="w3layouts_social_list media-soc list-unstyled">
                    <li>
                        <a href="#" class="w3pvt_facebook editContent">
                            <span class="fa fa-facebook-f"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_twitter editContent">
                            <span class="fa fa-twitter"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_dribble editContent">
                            <span class="fa fa-dribbble"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_google editContent">
                            <span class="fa fa-google-plus"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8 footer-right">
                <div class="w3layouts-news-letter">
                    <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">Newsletter</h3>

                    <p class="editContent">By subscribing to our mailing list you will always get latest news and
                        updates from us.</p>
                    <form action="#" method="post" class="w3layouts-newsletter">
                        <input type="email" name="Email" class="editContent" placeholder="Enter your email..."
                               required="">
                        <button class="btn1 btn"><span class="fa fa-paper-plane-o" aria-hidden="true"></span>
                        </button>

                    </form>
                </div>
                <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">Разделы</h3>
                        <ul class="list-unstyled w3layouts-icons">
                            <li>
                                <a href="index.html" class="editContent">Главная</a>
                            </li>
                            <li>
                                <a href="about.html" class="editContent">Категории</a>
                            </li>
                            <li>
                                <a href="contact.html" class="editContent">Контакты</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <!-- social icons -->
                        <div class="agileinfo_social_icons">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">Pages</h3>
                            <ul class="list-unstyled w3layouts-icons">

                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- social icons -->
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                        <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent">Contact Info</h3>
                        <div class="contact-info">
                            <div class="footer-address-inf my-4">
                                <h4 class="ad-info mb-2 editContent">Email </h4>
                                <p class="editContent"><a href="mailto:info@example.com">info@example.com</a></p>
                            </div>
                            <div class="footer-address-inf">
                                <h4 class="ad-info mb-2 editContent">Location</h4>
                                <p class="editContent">New York City</p>
                            </div>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </div>
</footer>
<div class="cpy-right py-3">
    <div class="container">
        <div class="row">
            <p class="col-md-10 text-left">© 2019 DjangoMovie. All rights reserved | Design by
                <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
            </p>
            <a href="#home" class="move-top text-right col-md-2">
                <span class="fa fa-long-arrow-up" aria-hidden="true"></span></a>
        </div>
    </div>
</div>

backend/templates/inc/_header.html
{% load movies_tags %}

<div class="main-banner bg bg1" id="home" style="background-color: rgba(0, 0, 0, 0); margin-top: 0px;">
    <header class="header">
        <div class="container-fluid px-lg-5">
            <nav class="py-4">
                <div id="logo">
                    <h1>
                        <a href="{% url 'movie_list' %}" class="editContent" style="outline: none; outline-offset: -2px; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">Netflix</a>
                    </h1>
                </div>

                <label for="drop" class="toggle">Menu</label>
                <input type="checkbox" id="drop">
                <ul class="menu mt-2">
                    <li class="active"><a href="index.html">Главная</a></li>
                    <li>

                        <!-- First Tier Drop Down -->
                        <label for="drop-2" class="toggle">Категории <span class="fa fa-angle-down"
                                                                           aria-hidden="true"></span> </label>
                        <a href="#">Категории <span class="fa fa-angle-down" aria-hidden="true"></span></a>
                        <input type="checkbox" id="drop-2">
                        <ul>
                            {% get_categories as categories %}
                            {% for category in categories %}
                                <li><a href="/">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="contact.html"
                           style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a>
                    </li>
                </ul>
            </nav>
            <!-- //nav -->
        </div>
    </header>
    <!-- //header -->
    <!--/banner-->
    <div class="banner-info">
        <p class="editContent">лучший сайт на django 3</p>
        <h3 class="mb-4 editContent">Все о кино</h3>
        <div class="ban-buttons">


        </div>
    </div>
    <!--// banner-inner -->

</div>